services:
  redis:
    image: redis:alpine
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '150MB'
    network_mode: 'host'
  postgres:
    image: pgvector/pgvector:pg17
    environment:
      POSTGRES_USER: parkinglot2
      POSTGRES_PASSWORD: parkinglot1232
      POSTGRES_DB: parkinglot2
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: '400MB'
    network_mode: 'host'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s