CREATE EXTENSION vector;

CREATE TABLE IF NOT EXISTS public.PARKING_SPACE(
   CODE VARCHAR(10) NOT NULL,
   STATUS SMALLINT NOT NULL,
   CONSTRAINT PK_PARKING_SPACE PRIMARY KEY (CODE)
);

CREATE TABLE IF NOT EXISTS public.ALLOCATION(
    ID UUID NOT NULL,
    PARKINGSPACE_CODE VARCHAR(10) NOT NULL,
    CAR_PLATE VARCHAR(10) NOT NULL,
    CAR_COLOR VARCHAR(10) NOT NULL,
    ENTRY_DATE TIMESTAMP NOT NULL,
    EXIT_DATE TIMESTAMP,
    CONSTRAINT PK_ALLOCATION PRIMARY KEY (ID),
    CONSTRAINT FK_PARKING_SPACE FOREIGN KEY (PARKINGSPACE_CODE) REFERENCES PARKING_SPACE(CODE)
);

CREATE TABLE IF NOT EXISTS public.PAYMENT(
    ID UUID NOT NULL,
    ALLOCATION_ID UUID NOT NULL,
    VALUE NUMERIC(10,2) NOT NULL,
    PAYMENT_DATE TIMESTAMP NOT NULL,
    CONSTRAINT PK_PAYMENT PRIMARY KEY (ID),
    CONSTRAINT FK_ALLOCATION FOREIGN KEY (ALLOCATION_ID) REFERENCES ALLOCATION(ID)
);

CREATE TABLE IF NOT EXISTS public.PRICE(
    ID UUID NOT NULL,
    DESCRIPTION VARCHAR(100) NOT NULL,
    VALUE NUMERIC(10, 2) NOT NULL,
    CONSTRAINT PK_PRICE PRIMARY KEY (ID)
);

ALTER TABLE IF EXISTS public.ALLOCATION
    OWNER to parkinglot2;

ALTER TABLE IF EXISTS public.PAYMENT
    OWNER to parkinglot2;

ALTER TABLE IF EXISTS public.PARKING_SPACE
    OWNER to parkinglot2;

ALTER TABLE IF EXISTS public.PRICE
    OWNER to parkinglot2;

INSERT INTO public.PRICE (ID, DESCRIPTION, VALUE) VALUES (gen_random_uuid(), 'First Hour', 5.00);
INSERT INTO public.PRICE (ID, DESCRIPTION, VALUE) VALUES (gen_random_uuid(), 'Other Hour', 3.00);

INSERT INTO public.PARKING_SPACE (CODE, STATUS) VALUES ('A1', 0), ('A2', 0), ('A3', 0), ('A4', 0), ('A5', 0);