services:
  redis:
    image: redis:alpine
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '150MB'
    network_mode: 'host'
  postgres:
    image: pgvector/pgvector:pg17
    environment:
      POSTGRES_USER: parkinglot
      POSTGRES_PASSWORD: parkinglot123
      POSTGRES_DB: parkinglot
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: '400MB'
    network_mode: 'host'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '150MB'
    network_mode: 'host'
  parking-lot-integration-api:
    image: junior/parkinglot-integration-api:1.0.0
    environment:
      - TZ=America/Sao_Paulo
    depends_on:
      postgres:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '0.8'
          memory: '150MB'
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:8081/q/health || exit 1"]
      interval: 40s
      timeout: 30s
      retries: 5
      start_period: 60s
    network_mode: 'host'